TwitApp/models.py
from datetime import datetime
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

from TwitApp import db


class Tweet(db.Model):

    __tablename__ = 'Tweets'

    id = db.Column(db.Integer, primary_key=True)
    rand_id = db.Column(db.Integer)
    tag = db.Column(db.String())
    tweet_id = db.Column(db.String())
    lang = db.Column(db.String())
    text = db.Column(db.String())
    sentiment = db.Column(db.Float)
    datetime = db.Column(db.String())

    def __init__(self, rand_id, tag, tweet_id, lang, text):
        self.rand_id = rand_id
        self.tag = tag
        self.tweet_id = tweet_id
        self.lang = lang
        self.text = text
        self.sentiment = SentimentIntensityAnalyzer().polarity_scores(text)['compound']
        self.datetime = str(datetime.now())

    @classmethod
    def save_all_to_db(cls, tweet_list):
        if tweet_list:
            db.session.add_all(tweet_list)
            db.session.commit()

    @classmethod
    def del_all_by_key(cls, tag, rand_id):
        cls.query.filter_by(tag=tag, rand_id=rand_id).delete()
        db.session.commit()

    def save_to_db(self):
        db.session.add(self)
        db.session.commit()

    def delete_from_db(self):
        db.session.delete(self)
        db.session.commit()

TwitApp/forms.py
from wtforms import Form, StringField, IntegerField, validators


class TweetForm(Form):
    search_key = StringField('search_key',
                             validators=[validators.InputRequired()])
    tweet_count = IntegerField('tweet_count',
                               validators=[validators.InputRequired()])

TwitApp/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

from TwitApp.config import Config

db = SQLAlchemy()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)

    from TwitApp.routes import tweet
    app.register_blueprint(tweet)

    @app.before_first_request
    def create_tables():
        db.create_all()

    return app

TwitApp/routes.py
from flask import Blueprint, request, render_template

from TwitApp.data import TwitterMain
from TwitApp.forms import TweetForm

tweet = Blueprint('tweet', __name__)

title = 'Twitter Sentiment Analyser'


@tweet.route('/')
def my_form():
    form = TweetForm(request.form)
    return render_template('index.html', title=title, form=form)


@tweet.route('/', methods=['POST'])
def my_form_post():
    text = request.form['search_key']
    count = int(request.form['tweet_count'])
    twit_main = TwitterMain()
    tweets, rand_id = twit_main.get_trends(text, count)
    return render_template('disp.html', title=title,
                           search_key=text, rand_id=rand_id,
                           render_list=tweets)


@tweet.route('/analysis/<key>/<int:rand_id>')
def analysis(key, rand_id):
    data = TwitterMain.get_analysis_data(key, rand_id)
    return render_template('analysis.html', title=title,
                           search_key=key, data=data)

TwitApp/templates/analysis.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{ title }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{{ url_for( 'static', filename='images/favicon.ico') }}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/bootstrap.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/font-awesome.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/animate.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/hamburgers.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/select2.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/util.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/main.css') }}">
<!--===============================================================================================-->
	<script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/1.0.2/Chart.min.js'></script>
	<script src="{{ url_for( 'static', filename='js/Chart.bundle.js') }}"></script>
	<script src="{{ url_for( 'static', filename='js/utils.js') }}"></script>
</head>
<body>

	<div class="bg-contact2" style="background-image: url('{{ url_for( 'static', filename='images/bg-01.jpg') }}');">
		<div class="container-contact2">
			<div class="wrap-contact2">
				<span class="contact2-form-title">
					{{ title }}
				</span>
				<br>
				<div align="center">
					<h3>Tweet Analysis for key : <i>{{ search_key }}</i></h3>
					<br>				
					<canvas id="chart-area" width="600" height="400"></canvas>
					<br>
					<br>
					<h4>Want to try analysis on different search key ?</h4>
					<div class="container-contact2-form-btn">
						<div class="wrap-contact2-form-btn">
							<div class="contact2-form-bgbtn"></div>
							<a href="{{ url_for('tweet.my_form') }}" class="contact2-form-btn" role="button">Yes</a>
						</div>
					</div>
					<script>
						var config = {
							type: 'pie',
							data: {
								datasets: [{
									data: {{ data }},
									backgroundColor: [
										"#ff5c33",
										"#66ff66",
										"#6699ff"
									],
									label: 'Sentiment Data'
								}],
								labels: [
									'Negative',
									'Positive',
									'Neutral'
								]
							},
							options: {
								responsive: true
							}
						};

						window.onload = function() {
							var ctx = document.getElementById('chart-area').getContext('2d');
							window.myPie = new Chart(ctx, config);
						};

					</script>
				</div>	
			</div>
		</div>
	</div>
	



<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/jquery-3.2.1.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/popper.js') }}"></script>
	<script src="{{ url_for( 'static', filename='js/bootstrap.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/select2.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/main.js') }}"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-23581568-13');
	</script>

</body>
</html>

TwitApp/templates/disp.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{ title }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{{ url_for( 'static', filename='images/favicon.ico') }}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/bootstrap.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/font-awesome.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/animate.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/hamburgers.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/select2.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/util.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/main.css') }}">
<!--===============================================================================================-->
</head>
<body>

	<div class="bg-contact2" style="background-image: url('{{ url_for( 'static', filename='images/bg-01.jpg') }}');">
		<div class="container-contact2">
			<div class="wrap-contact2">
				<span class="contact2-form-title">
					{{ title }}
				</span>
				<br>
				<div class="container-contact2-form-btn">
					<div class="wrap-contact2-form-btn">
						<div class="contact2-form-bgbtn"></div>
						<a href="{{ url_for('tweet.analysis', key=search_key, rand_id=rand_id) }}" class="contact2-form-btn" role="button">Analyze</a>
					</div>
				</div>
				<br>
				<div align="center">
					<h3>Search results for search key : <i>{{ search_key }}</i></h3>
					<br>
					{% for tweet in render_list %}
					<div id ="twitter-tweets">
					{{ tweet|safe }}
					</div>
					{% endfor %}
				</div>	
			</div>
		</div>
	</div>




<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/jquery-3.2.1.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/popper.js') }}"></script>
	<script src="{{ url_for( 'static', filename='js/bootstrap.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/select2.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/main.js') }}"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-23581568-13');
	</script>

</body>
</html>

TwitApp/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>{{ title }}</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->
	<link rel="icon" type="image/png" href="{{ url_for( 'static', filename='images/favicon.ico') }}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/bootstrap.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/font-awesome.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/animate.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/hamburgers.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/select2.min.css') }}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/util.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ url_for( 'static', filename='css/main.css') }}">
<!--===============================================================================================-->
	<script>
	function validateForm() {
		var key = document.forms["login_form"]["search_key"].value;
		var count = document.forms["login_form"]["tweet_count"].value;
		if (key == "") {
			alert("Search key must be filled out");
			return false;
		}
		if (count == "") {
			alert("Tweet count must be filled out");
			return false;
		}
		if (count > 100) {
			alert("Please enter a value less than 100");
			return false;
		}
		if (count < 10) {
			alert("Please enter a value greater than 10")
			return false
		}
		document.getElementById("gif").style.visibility = "visible";
	}
	</script>
	
</head>
<body>

	<div class="bg-contact2" style="background-image: url('{{ url_for( 'static', filename='images/bg-01.jpg') }}');">
		<div class="container-contact2">
			<div class="wrap-contact2">
				<form class="contact2-form validate-form" name="login_form" id="login_form" action="" onsubmit="return validateForm()" method="POST" novalidate>
					<span class="contact2-form-title">
						{{ title }}
					</span>
					<img src="{{ url_for( 'static', filename='images/loading.gif') }}" id="gif" style="display: block; margin: 0 auto; width: 100px; visibility: hidden;">
					<div class="wrap-input2 validate-input" data-validate="Search Key is required">
						{{ form.search_key(class="input2") }}
						<span class="focus-input2" data-placeholder="Search Key"></span>
					</div>
					<div class="wrap-input2 validate-input" data-validate="Tweet count is required">
						{{ form.tweet_count(class="input2") }}
						<span class="focus-input2" data-placeholder="Tweet Count"></span>
					</div>
					
					<div class="container-contact2-form-btn">
						<div class="wrap-contact2-form-btn">
							<div class="contact2-form-bgbtn"></div>
							<button class="contact2-form-btn" id="form-button">
								Submit
							</button>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>



<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/jquery-3.2.1.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/popper.js') }}"></script>
	<script src="{{ url_for( 'static', filename='js/bootstrap.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/select2.min.js') }}"></script>
<!--===============================================================================================-->
	<script src="{{ url_for( 'static', filename='js/main.js') }}"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-23581568-13');
	</script>	
	
</body>
</html>